In [8]:
#!/usr/bin/env python

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling

from utils import *

ONE_STATION, NEARBY_STATION = False, True

def build_model(num_classes):
    model = keras.Sequential([
        keras.layers.Dense(128, activation='relu'),
        keras.layers.Dropout(0.2),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam',
                  loss=tf.keras.losses.SparseCategoricalCrossentropy(),
                  metrics=['accuracy'])
    return model


file_path = "ghcnd_hcn/pair_final.csv"
df = pd.read_csv(file_path)
df

,STATION,LAT,LON,ELEV,DATE,PRCP1,TMAX1,TMIN1,SNOW1,SNOWD1,PRCP2,TMAX2,TMIN2,SNOW2,SNOWD2
0,USC00011084,31.0583,-87.0550,25.9,722815.0,0.0,122.0,0.0,0.0,0.0,0.0,122.0,0.0,0.0,0.0
1,USC00011084,31.0583,-87.0550,25.9,722817.0,0.0,122.0,0.0,0.0,0.0,0.0,122.0,0.0,0.0,0.0
2,USC00011084,31.0583,-87.0550,25.9,722819.0,0.0,122.0,0.0,0.0,0.0,0.0,122.0,0.0,0.0,0.0
3,USC00011084,31.0583,-87.0550,25.9,722821.0,0.0,122.0,0.0,0.0,0.0,0.0,122.0,0.0,0.0,0.0
4,USC00011084,31.0583,-87.0550,25.9,722823.0,0.0,122.0,0.0,0.0,0.0,0.0,122.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524060,USC00450945,47.1694,-122.0036,208.8,734127.0,89.0,117.0,56.0,0.0,0.0,89.0,117.0,56.0,0.0,0.0
524061,USC00450945,47.1694,-122.0036,208.8,734129.0,89.0,117.0,56.0,0.0,0.0,89.0,117.0,56.0,0.0,0.0
524062,USC00450945,47.1694,-122.0036,208.8,734131.0,89.0,117.0,56.0,0.0,0.0,89.0,117.0,56.0,0.0,0.0
524063,USC00450945,47.1694,-122.0036,208.8,734133.0,89.0,117.0,56.0,0.0,0.0,89.0,117.0,56.0,0.0,0.0
524064,USC00450945,47.1694,-122.0036,208.8,734135.0,89.0,117.0,56.0,0.0,0.0,89.0,117.0,56.0,0.0,0.0

In [9]:
X_train, X_test, y_train, y_test = nearby_station_split(
            df, 'USC00057936', 'Precipitation', False)

TypeError: nearby_station_split() takes 3 positional arguments but 4 were given